name: Keep Repository Active

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at 5:30 AM IST on the 1st and 15th of every month
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Keep repo active with dummy commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          date >> keepalive.txt
          git add keepalive.txt
          git commit -m "Keep repository active"
          git push
