name: Birthday Checker Daily

on:
  schedule:
    - cron: '55 0 * * *'  # Runs daily at 2:25 AM IST (20:55 UTC)
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull gowthamkubendran034/birthday-checker:latest

      - name: Run Birthday Checker
        run: |
          docker run --rm \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASS="${{ secrets.DB_PASS }}" \
            -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
            gowthamkubendran034/birthday-checker:latest
